image: docker:stable

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - chmod +x ci/dependencies.sh
          - docker-compose up -d
          - docker-compose down
