version: '3.1'

services:
  backend:
    container_name: backend
    image: backend
    volumes:
      - workspace:/Users/root/finder_workspace
    ports:
      - '3333:3333'
    networks:
      - backend

  frontend:
    container_name: frontend
    image: frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - backend

volumes:
  workspace:

networks:
  backend:
    driver: bridge
