version: '3.1'

services:

  backend:
    container_name: backend
    image: backend
    ports:
      - "3333:3333"
    networks:
     - backend

  frontend:
    container_name: frontend
    image: frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - backend


networks:
  backend:
    driver: bridge
